version: '3.10'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=matheus19dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:



# version: '3'

# services:
#   db:

#      image: 'postgres'
#      ports:
#        - '5432'

#   core:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     command: python3 manage.py runserver 0.0.0.0:8000
#     ports:
#       - '8000:8000'
#     volumes:
#       - .:/code
#     depends_on:
#       - db
#     links:
#       - db:db
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=matheus19dev

#   #   networks:
#   #     some_network:
#   # networks:
#   #  some_network: