# Generated by Django 4.0.3 on 2022-04-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_hermes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-added',)},
        ),
    ]
